#ifndef _KERNEL_ARCH_TRAMPOLINE_H
#define _KERNEL_ARCH_TRAMPOLINE_H

#include <stdint.h>

// Physical address where the trampoline code + data is copied at runtime.
// Must be below 1MB (real-mode addressable) and page-aligned for SIPI.
#define TRAMPOLINE_BASE         0x8000UL

// trampoline_data is placed at fixed offset 0x200 from the binary
// start by the trampoline.S .org directive (= physical 0x8200).
#define TRAMPOLINE_DATA_OFFSET  0x200UL
#define TRAMPOLINE_DATA_BASE    (TRAMPOLINE_BASE + TRAMPOLINE_DATA_OFFSET)

// ── Trampoline data page layout ───────────────────────────
// Filled by the BSP before sending SIPI to each AP.
// Must match the layout in kernel/arch/x86_64/trampoline.S.
typedef struct {
    uint64_t cr3;        // offset 0:  PML4 physical address
    uint64_t gs_base;    // offset 8:  per-CPU data (VA for IA32_GS_BASE MSR)
    uint64_t stack;      // offset 16: initial kernel stack pointer (VA)
    uint64_t entry;      // offset 24: C entry point (ap_entry)
    uint32_t apic_id;    // offset 32: this AP's LAPIC ID
    uint32_t cpu_id;     // offset 36: logical CPU number (index into percpu_data[])
} __attribute__((packed)) trampoline_data_t;

// ── Embedded trampoline binary (linked via ld -r -b binary) ──
// The BSP copies this blob to TRAMPOLINE_BASE at runtime.
// Symbols are generated by the linker from the filename.
extern char _binary_arch_x86_64_trampoline_bin_start[];
extern char _binary_arch_x86_64_trampoline_bin_end[];

// ── SMP boot API ──────────────────────────────────────────

// Bring up all APs discovered from MADT (Phase 1 enumeration).
// Copies the trampoline to 0x8000, then sends INIT-SIPI-SIPI
// to each online-capable AP in percpu_data[].
void smp_boot_aps(void);

#endif
